name: "Test"
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - '*.md'

jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  # Run unit tests
  tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: Install dependencies and run tests
        run: |
          go mod download
          go test -v ./...